/* Read-only slide conversion. The source's text and order are retained. */
(()=>{'use strict';const D=window.ETOPS_PRESENTATION,$=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
if(!D||!Array.isArray(D.slides)||D.slides.length!==20){$('slideHost').textContent='No se pudo cargar la presentación. Actualiza la página.';return;}
let page=0;const node=(tag,attrs={})=>{const n=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));return n;};
function makeSlide(index){const s=D.slides[index],svg=node('svg',{viewBox:`0 0 ${D.width} ${D.height}`,role:'img','aria-label':`${index+1}. ${D.titles[index]}`});
for(const v of s[0]){const [kind,x,y,w,h,fill,stroke,width]=v;let el;if(kind===2){el=node('line',{x1:x,y1:y,x2:w,y2:h,stroke:D.colors[fill]||'none','stroke-width':stroke});}else{el=kind===1?node('ellipse',{cx:x+w/2,cy:y+h/2,rx:w/2,ry:h/2}):node('rect',{x,y,width:w,height:h});el.setAttribute('fill',D.colors[fill]||'none');el.setAttribute('stroke',D.colors[stroke]||'none');el.setAttribute('stroke-width',width);}svg.appendChild(el);}
for(const [x,y,w,k,text] of s[1]){const st=D.styles[k],el=node('text',{x,y,fill:D.colors[st[1]],'font-size':st[0],'font-style':st[2]?'italic':'normal','xml:space':'preserve'});if(w>0){el.setAttribute('textLength',w);el.setAttribute('lengthAdjust','spacingAndGlyphs');}el.textContent=text;svg.appendChild(el);}return svg;}
function position(){const m=/^slide-(\d+)$/.exec(location.hash.slice(1));return m?Math.min(D.slides.length-1,Math.max(0,Number(m[1])-1)):0;}
function paint(){page=position();$('slideHost').replaceChildren(makeSlide(page));$('slideSelect').value=String(page);$('slideTitle').textContent=D.titles[page];$('counter').textContent=`${page+1} / ${D.slides.length}`;$('position').textContent=`Diapositiva ${page+1} de ${D.slides.length}`;$('prev').disabled=page===0;$('next').disabled=page===D.slides.length-1;$('transcript').replaceChildren(...D.slides[page][1].map(v=>{const p=document.createElement('p');p.textContent=v[4];return p;}));$('viewport').scrollLeft=0;}
function go(n){const next=Math.max(0,Math.min(D.slides.length-1,n));if(next===page)return;location.hash=`slide-${next+1}`;}
D.titles.forEach((t,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${String(i+1).padStart(2,'0')} · ${t}`;if(i===0)$('slideSelect').replaceChildren(o);else $('slideSelect').appendChild(o);});
$('slideSelect').addEventListener('change',e=>go(Number(e.target.value)));$('prev').addEventListener('click',()=>go(page-1));$('next').addEventListener('click',()=>go(page+1));$('zoom').addEventListener('change',e=>{$('slideHost').style.width=(Number(e.target.value)*100)+'%';});
document.addEventListener('keydown',e=>{if(e.target instanceof Element&&e.target.closest('select,button,input,textarea,summary,a'))return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();go(page+(e.key==='ArrowRight'?1:-1));}});
function printPages(){const out=$('printPages');if(out.childElementCount)return;D.slides.forEach((_,i)=>{const p=document.createElement('section');p.className='print-slide';p.appendChild(makeSlide(i));out.appendChild(p);});}
$('print').addEventListener('click',()=>{printPages();window.print();});window.addEventListener('beforeprint',printPages);window.addEventListener('afterprint',()=>$('printPages').replaceChildren());window.addEventListener('hashchange',paint);paint();})();
