/* ETOPS Classroom 1.0 — source-led learning, not an operational calculator. */
window.ETOPS_CONTENT = {
  version:'1.0.0', reviewed:'26 septiembre 2026',
  sources:[
    {id:'BASE',title:'Material base de Veyra',detail:'modulo-etops.pdf (17 páginas), Veyra_Modulo_ETOPS.pptx (20 diapositivas) y etops-quiz.pdf (20 preguntas). Contenido adaptado; las correcciones se documentan en esta clase.',url:''},
    {id:'DEF',title:'FAA · 14 CFR 1.1 y 121.161',detail:'Definición de ETOPS y limitaciones de ruta. Texto eCFR consultado el 26/09/2026.',url:'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-G/part-121/subpart-H/section-121.161'},
    {id:'GLOSS',title:'FAA · 14 CFR 1.1',detail:'Definiciones: Extended Operations y sistemas significativos ETOPS.',url:'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-A/part-1/section-1.1'},
    {id:'APP',title:'FAA · Apéndice P de la Parte 121',detail:'Aprobaciones y condiciones específicas; incluye excepciones que impiden convertir una cifra en regla universal.',url:'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-G/part-121/appendix-Appendix%20P%20to%20Part%20121'},
    {id:'ALT',title:'FAA · 14 CFR 121.624',detail:'Alternos ETOPS, ventana de uso, condiciones de campo y mínimos autorizados en OpSpecs.',url:'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-G/part-121/subpart-U/section-121.624'},
    {id:'EEP',title:'FAA · 14 CFR 121.631(c)–(e)',detail:'Condiciones antes de continuar más allá del EEP; mínimos operacionales, revisión de alternos y capacidades.',url:'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-G/part-121/subpart-U/section-121.631'},
    {id:'FUEL',title:'FAA · 14 CFR 121.646(b)',detail:'Tres escenarios en el punto más crítico, viento, hielo, deterioro, espera y APU.',url:'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-G/part-121/subpart-U/section-121.646'},
    {id:'TLS',title:'FAA · 14 CFR 121.633',detail:'Sistemas limitados por tiempo: bases distintas para hasta 180 y más de 180 minutos.',url:'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-G/part-121/subpart-U/section-121.633'},
    {id:'MAINT',title:'FAA · 14 CFR 121.374',detail:'CAMP ETOPS: chequeo previo, mantenimiento dual, fiabilidad, aceite, APU y CMP.',url:'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-G/part-121/subpart-L/section-121.374'},
    {id:'REL',title:'FAA · 14 CFR 21.4(b)(2)',detail:'Niveles IFSD de la flota mundial; no confundir con los umbrales de revisión del operador de 121.374(i).',url:'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-C/part-21/subpart-A/section-21.4'},
    {id:'DIV',title:'FAA · 14 CFR 121.565',detail:'Motor inoperativo: aeropuerto adecuado más cercano en tiempo donde se pueda aterrizar con seguridad; excepciones para tres o más motores.',url:'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-G/part-121/subpart-T/section-121.565'},
    {id:'EU',title:'EASA · Easy Access Rules for Air Operations',detail:'Referencia de consulta Part-SPA ETOPS y CAT.OP.MPA.140. La página oficial consultada identifica revisión 24, marzo 2026. No se usa aquí como tabla de despacho de un operador.',url:'https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-air-operations'},
    {id:'ICAO',title:'OACI · Anexo 6, Parte I, 4.7',detail:'Referencia identificada en el material recibido para EDTO. No se recibió ni se verificó una copia íntegra vigente del Anexo 6; no se reproducen límites operacionales nacionales a partir de él.',url:''}
  ],
  modules:[
    {id:1,kicker:'COMPRENDER',title:'Qué protege ETOPS',subtitle:'No es una autorización para cruzar agua. Es una forma de conservar opciones.',time:'8–12 min',base:'PDF §§0.1–0.5 · diapositivas 1–7',refs:['BASE','DEF','GLOSS','ICAO','EU'],lab:'framework',
      goal:'Distinguir el concepto operacional de la sigla y reconocer qué marco normativo estás leyendo.',
      blocks:[
        {title:'La pregunta antes de la sigla',text:'Imagina una ruta lejos de aeródromos utilizables. El avión funciona normalmente, pero tienes que demostrar qué ocurriría si deja de hacerlo. ETOPS organiza esa demostración: capacidad técnica, fiabilidad, mantenimiento, despacho, entrenamiento y opciones de desvío. El tiempo de alejamiento no describe cuánto dura el vuelo completo ni cuánto combustible adicional debe llevarse.'},
        {title:'FAA: Extended Operations',text:'En el marco de 14 CFR, la definición excluye las operaciones exclusivamente de carga en aviones con más de dos motores. La Parte 121 establece, salvo aprobación aplicable, 60 minutos para bimotores de turbina y 180 para aviones de pasajeros con más de dos motores, a velocidad OEI aprobada en condiciones estándar y aire en calma. Por tanto, «FAA: todos los aviones» es una simplificación incorrecta. Las operaciones polares tienen requisitos propios; no son sinónimo de ETOPS.'},
        {title:'EASA y OACI: leer el contexto',text:'El material presenta ETOPS en EASA para aviones de dos motores; el umbral concreto se consulta en el marco aplicable, no se extiende automáticamente a todo avión pequeño. OACI utiliza EDTO, Extended Diversion Time Operations, para operaciones de aviones con dos o más motores de turbina más allá del umbral que establece el Estado del operador. Comparten la lógica de gestionar una desviación prolongada, pero no son reglas jurídicamente intercambiables. Esta clase no concede una aprobación ni reemplaza el marco de tu Estado.'},
        {title:'La historia que sí ayuda a comprender',text:'La secuencia del material base recorre la regla de 60 minutos de 1953, la guía de 120 minutos de 1985, la ampliación de 1988, la regla FAA de 2007 y la introducción de EDTO en 2012. La lección es la evolución basada en evidencia. No necesitas memorizar una fecha de un vuelo inaugural para decidir bien. Se retiraron del contenido evaluable los multiplicadores «100 veces / 60 veces» y las fechas de certificación por variante no corroboradas con documentación de tipo.'}
      ],takeaway:'Primero identifica la autoridad, el tipo de operación y el avión; después interpreta los minutos.',
      check:{q:'Una ruta sobre una zona continental remota puede requerir ETOPS aunque no cruce un océano. ¿Por qué?',options:['Porque la condición relevante es el alejamiento de aeródromos, bajo el marco aplicable.','Porque ETOPS significa operación exclusivamente oceánica.','Porque todos los vuelos de más de una hora son ETOPS.'],correct:0,feedback:'La distancia de la costa y la duración total del vuelo no definen por sí solas ETOPS. La referencia es el tiempo a un aeródromo adecuado.'}},
    {id:2,kicker:'AUTORIZAR',title:'Dos límites, dos demostraciones',subtitle:'Que el avión pueda no significa que ese vuelo esté autorizado.',time:'10–14 min',base:'PDF §§0.7, 0.12–0.13 · diapositivas 9, 15–16',refs:['BASE','APP','REL','MAINT'],lab:'approval',
      goal:'Separar tiempo umbral, tiempo autorizado, estado técnico y aprobación del operador.',
      blocks:[
        {title:'Umbral no es máximo',text:'El threshold time determina cuándo se activa el marco ETOPS/EDTO. El maximum diversion time define el alcance autorizado para una operación concreta. Una ruta puede estar más allá del umbral y todavía dentro de una autorización de 120 o 180 minutos. Esos valores no son NM y tampoco describen duración de vuelo.'},
        {title:'Diseño y operación',text:'La combinación avión–motor debe demostrar la capacidad técnica exigida, y el operador debe demostrar procedimientos, mantenimiento, despacho y entrenamiento. Para las aprobaciones FAA de 120 y 180 minutos, el Apéndice P exige capacidad de diseño al menos equivalente. No conviertas esto en un «nunca» universal: existen disposiciones específicas como ciertas operaciones de 75 minutos y extensiones condicionadas de 138/207 minutos. Una cifra comercial no sustituye la autorización concreta.'},
        {title:'El vuelo de hoy puede tener un límite menor',text:'La MEL puede impedir ETOPS o reducir el tiempo utilizable. También importan la configuración, los sistemas limitados por tiempo, los aeródromos disponibles y la ruta. El documento CMP recoge requisitos de configuración, mantenimiento y procedimientos cuando resulta aplicable. La ficha de despacho debe concordar con esa configuración, no solo con el nombre de la familia de avión.'},
        {title:'Fiabilidad: especifica qué tasa estás citando',text:'El material usa 0,05 / 0,02 / 0,01 IFSD por 1.000 horas de motor. La referencia FAA 21.4(b)(2) trata niveles de flota mundial y contiene condiciones y excepciones. En cambio, 121.374(i) fija umbrales de revisión del operador de 0,05 / 0,03 / 0,02 según alcance. No mezcles objetivos de diseño con disparadores de revisión operacional. La vía de experiencia en servicio y la acelerada requieren demostraciones; esta clase no promete aprobación tras un número fijo de meses.'}
      ],takeaway:'La autorización útil se demuestra con documentos y condiciones, no solo con un número en una tarjeta.',
      check:{q:'Ejercicio: diseño 180 min, autorización del operador 120 min y restricción MEL de 90 min. ¿Qué límite usa este caso?',options:['180 min: manda el diseño.','90 min: la restricción de este vuelo es más exigente.','120 min: la MEL no afecta ETOPS.'],correct:1,feedback:'En este supuesto, el techo es 90 minutos. Aún deben cumplirse alternos, combustible y demás requisitos; el mínimo de tres cifras no certifica un vuelo real.'}},
    {id:3,kicker:'TRAZAR',title:'El tiempo dibuja la ruta',subtitle:'EEP, EXP, ETP y punto crítico: cuatro ideas, no cuatro sinónimos.',time:'12–18 min',base:'PDF §§0.6–0.8 · diapositivas 8–10',refs:['BASE','DEF','FUEL'],lab:'geometry',
      goal:'Convertir minutos a millas y explicar por qué un punto de tiempo igual no es automáticamente el punto crítico de combustible.',
      blocks:[
        {title:'De minutos a millas sin perder las unidades',text:'Para la referencia bimotor utilizada en el material: distancia en NM = TAS OEI aprobada en kt × tiempo en minutos / 60, en condiciones estándar y aire en calma. Con 400 kt y 120 minutos obtienes 800 NM. Ese radio no es la trayectoria real del día: viento, altitud, temperatura y configuración afectan el desvío real.'},
        {title:'Cobertura y entrada',text:'El EEP es el primer punto de la ruta que entra en la zona más allá del umbral aplicable respecto de los aeródromos adecuados. EXP marca la salida de ese segmento. Puede haber más de un segmento. El EEP no es por definición el punto de no retorno ni garantiza que regresar sea sencillo. En el esquema se muestran dos aeródromos ficticios para aislar la geometría, no para aprobar una ruta.'},
        {title:'ETP: igualdad de tiempo',text:'Un Equal Time Point depende de las velocidades respecto al suelo hacia ambos alternos bajo un escenario definido. En una línea de longitud D, si x se mide desde A: x/GS hacia A = (D−x)/GS hacia B. De ahí x = D × GS hacia A / (GS hacia A + GS hacia B). Si vuelas más lento hacia A, el ETP se acerca a A. Cambiar viento o escenario cambia el ETP.'},
        {title:'Punto crítico: exigencia de combustible',text:'El cálculo debe identificar el punto más crítico y comparar los escenarios aplicables. Igualar tiempos no garantiza igualar consumo: cambian flujo de combustible, altitud, viento, desvío y reservas. Un ETP es una referencia útil de planificación, pero no debe declararse automáticamente el único sitio ni el sitio más desfavorable para combustible. Esta distinción corrige el uso ETP / Critical Point del glosario original.'}
      ],takeaway:'El círculo es una referencia; el ETP iguala tiempos; el punto crítico se determina con el análisis de combustible.',
      check:{q:'Si las velocidades hacia A y B son distintas, ¿dónde debe estar el ETP?',options:['Siempre a mitad de la distancia.','En el EEP, independientemente del viento.','Donde se igualan los tiempos calculados para ese escenario.'],correct:2,feedback:'La mitad geométrica solo coincide con el ETP cuando las velocidades efectivas son iguales en este modelo lineal.'}},
    {id:4,kicker:'SELECCIONAR',title:'Un alterno debe seguir siendo una opción',subtitle:'La pista, el pronóstico y la ventana cuentan una historia conjunta.',time:'12–16 min',base:'PDF §§0.8–0.9 · diapositivas 10–12',refs:['BASE','ALT','EEP','EU'],lab:'weather',
      goal:'Diferenciar adecuación, mínimos de planificación y revisión en ruta sin mezclar jurisdicciones.',
      blocks:[
        {title:'Adecuado no significa solo «la pista cabe»',text:'Longitud y performance son parte de la evaluación, pero también disponibilidad, servicios, ayudas, aproximaciones, condiciones de campo y restricciones. Un cierre por NOTAM no desaparece porque el aeródromo tenga una pista larga. La aptitud para el vuelo exige comprobar además meteorología y ventana de uso conforme a la autorización.'},
        {title:'Despacho: usa los mínimos autorizados',text:'FAA 121.624 remite a los mínimos de alterno ETOPS de las OpSpecs y requiere que el campo permita un aterrizaje seguro durante la ventana desde la llegada más temprana hasta la más tardía. En el laboratorio se conservan los incrementos +400 ft/+1 SM y +200 ft/+½ SM del material como reglas proporcionadas por el ejercicio, no como tabla universal de despacho. No se publican los valores CAT II/III originales como autorización genérica.'},
        {title:'Antes del EEP no repitas ciegamente el despacho',text:'FAA 121.631(c) requiere pronósticos al menos en los mínimos operacionales durante la ventana de uso y revisar los alternos dentro del tiempo autorizado, informando cambios a la tripulación. Las capacidades de sistemas también pueden exigir actualizar el plan. La frase «antes del EEP siempre deben cumplirse los mismos mínimos de planificación» no refleja esa distinción FAA.'},
        {title:'Después del EEP: reevaluación, no piloto automático conceptual',text:'Estar por debajo de un mínimo de planificación no impone por sí solo un desvío inmediato; tampoco es permiso automático para continuar. Revisa los mínimos aplicables, evolución meteorológica, campo, sistemas, combustible y alternativas con despacho. Para EASA/OACI utiliza la norma y el manual vigentes: la ventana ±1 hora del material no se traslada aquí como regla universal. Un retraso cambia el intervalo que debes analizar.'}
      ],takeaway:'Comprueba el criterio correcto, en la fase correcta y para toda la ventana requerida.',
      check:{q:'En el ejemplo FAA, un alterno cae bajo mínimos de planificación pero sigue sobre los operacionales antes del EEP. ¿Conclusión?',options:['Aplicar 121.631, revisar alternos y capacidades; no decidir solo con el mínimo de despacho.','Continuar automáticamente porque ya despegó.','Declarar emergencia solo por esa diferencia.'],correct:0,feedback:'La fase y la norma importan. No equivale a una autorización automática de continuar ni a una obligación automática de desviarse.'}},
    {id:5,kicker:'COMPARAR',title:'Combustible: deja que gane el cálculo',subtitle:'Tres escenarios compiten. No elijas un ganador por memoria.',time:'14–20 min',base:'PDF §0.10 · diapositiva 13 · quiz 10–12',refs:['BASE','FUEL'],lab:'fuel',
      goal:'Comparar requisitos sobre una misma referencia e identificar el escenario limitante sin asumirlo.',
      blocks:[
        {title:'La pregunta correcta',text:'En el punto más crítico: ¿puedo llegar a un alterno bajo cada escenario exigido y conservar las cantidades requeridas? Se comparan motor inoperativo, despresurización, y despresurización con falla de motor. El caso combinado no gana por definición. La despresurización con ambos motores puede ser más exigente según sus condiciones de vuelo.'},
        {title:'La altitud no es una casilla fija',text:'El material usa FL100 como ejemplo. La referencia FAA exige una altitud segura que cumpla los requisitos de oxígeno; el terreno, las capacidades y el procedimiento importan. No enseñamos «siempre FL100». Tampoco usamos un flujo inventado como performance de una aeronave real: las cifras del laboratorio son supuestos completamente didácticos.'},
        {title:'Qué no debes omitir',text:'Además del tramo de desvío, considera los ajustes aplicables por viento, hielo y deterioro; 15 minutos de espera a 1.500 ft sobre el campo y aproximación y aterrizaje. El APU se incluye cuando es fuente requerida. FAA 121.646 no equivale a sumar siempre 5 % a todo: el ajuste de viento debe ser desfavorable, y existe alternativa de reserva si no se usa un modelo aceptado. El deterioro y el hielo tienen criterios propios.'},
        {title:'Compara desde el mismo punto',text:'No compares combustible remanente en un punto con combustible total de salida. Primero determina la exigencia máxima desde el punto crítico; después intégrala con el consumo hasta ese punto y los demás requisitos del plan normal sin omitir ni duplicar reservas. En el laboratorio todos los escenarios empiezan en el mismo punto y los ajustes aparecen ya agregados; no reproduce un sistema de despacho.'}
      ],takeaway:'Motor + despresurización es un escenario a calcular, no una respuesta que memorizar.',
      check:{q:'Requisitos ya completos desde el mismo punto: OEI 5.400 kg; despresurización 6.600 kg; combinado 6.000 kg. ¿Cuál manda?',options:['OEI, porque solo hay un motor.','Combinado, aunque la cifra sea menor.','Despresurización: 6.600 kg.'],correct:2,feedback:'Se toma el mayor requisito calculado. Elegir el combinado por costumbre dejaría 600 kg sin cubrir en este ejemplo.'}},
    {id:6,kicker:'VERIFICAR',title:'La desviación tiene un respaldo técnico',subtitle:'Un sistema que funciona ahora debe sostener la condición que estás planificando.',time:'12–16 min',base:'PDF §§0.11–0.12 · diapositivas 14–15',refs:['BASE','TLS','MAINT','GLOSS'],lab:'systems',
      goal:'Relacionar redundancia, duración de sistemas, mantenimiento y restricciones MEL.',
      blocks:[
        {title:'Significativo y limitado por tiempo no son lo mismo',text:'Un sistema significativo afecta la seguridad del desvío: puede contribuir a la propulsión, control o redundancia necesaria para vuelo prolongado. Un sistema limitado por tiempo tiene una capacidad temporal relevante. No todo sistema significativo se reduce a un cronómetro. Tampoco perder un motor implica perder exactamente la mitad de toda la capacidad eléctrica, hidráulica y neumática: depende de la arquitectura.'},
        {title:'195 − 15 = 180: ejemplo con contexto',text:'Bajo FAA 121.633(a), hasta e incluyendo 180 minutos, el tiempo a un alterno con la referencia OEI estándar/aire en calma no puede exceder el del sistema ETOPS significativo más limitante menos 15 minutos, incluyendo supresión de incendio aplicable. El cálculo 195−15 sirve para ese ejemplo. No demuestra por sí solo que un operador pueda volar ETOPS 180.'},
        {title:'Más allá de 180 cambia la comprobación',text:'FAA 121.633(b) diferencia supresión de incendio —tiempo a velocidad con todos los motores, corregido por viento y temperatura, frente a capacidad menos 15— y otros sistemas significativos con referencia OEI corregida. No se aplica indiscriminadamente «todo sistema menos 15» a cualquier aprobación. En vuelo, un incendio requiere el procedimiento y la decisión apropiada; una capacidad certificada no autoriza esperar a agotarla.'},
        {title:'Mantenimiento que protege la independencia',text:'El PDSC verifica estado de sistemas y registros; aceite y APU tienen programas específicos cuando corresponda. El mantenimiento dual puede introducir una causa común. FAA 121.374 restringe estas tareas y contempla condiciones cuando no se pueden evitar: técnicos diferentes o supervisión directa de otra persona calificada, más las verificaciones requeridas. Cambiar de técnico sin verificar no es una solución completa. CMP, MEL y registros deben ser consistentes.'}
      ],takeaway:'La redundancia se demuestra, se mantiene y se verifica; no se presume por contar motores.',
      check:{q:'El sistema del ejemplo soporta 195 min; el operador está autorizado a 120 min. ¿La resta de 15 permite planificar 180?',options:['Sí, porque 195−15=180.','No; 180 sería solo el techo del sistema en este supuesto, no la autorización del operador.','Sí, si se instala más combustible.'],correct:1,feedback:'La limitación de sistema y la autorización operacional son controles distintos. Deben satisfacerse ambos.'}},
    {id:7,kicker:'REEVALUAR',title:'Antes de entrar, vuelve a mirar',subtitle:'El despacho describe unas condiciones. El vuelo puede haberlas cambiado.',time:'10–14 min',base:'PDF §§0.9, 0.14 · diapositivas 11 y 17',refs:['BASE','EEP','ALT','FUEL'],lab:'entry',
      goal:'Relacionar una novedad antes del EEP con la información y coordinación que exige.',
      blocks:[
        {title:'Un chequeo no es recitar cuatro palabras',text:'Alternos: ¿siguen disponibles durante su ventana? Sistemas: ¿la capacidad actual coincide con la usada para planificar? Combustible: ¿el remanente previsto en el punto crítico cubre lo requerido? Comunicaciones: ¿puedo coordinar los cambios de plan? La verificación vale por las respuestas respaldadas, no porque alguien diga «ETOPS check completo».'},
        {title:'Lo que debe quedar conectado',text:'Un NOTAM de cierre puede cambiar cobertura. Un diferido puede cambiar tiempo permitido. Un viento nuevo puede cambiar tiempos y combustible. Una demora puede desplazar la ventana meteorológica. Las cuatro novedades pueden afectar al mismo vuelo aunque cada pantalla parezca correcta por separado. El caso que sigue es ficticio y usa una regla suministrada; no es una liberación real.'},
        {title:'Antes de cruzar',text:'En el ejemplo FAA se revisan los aeropuertos requeridos, mínimos operacionales y cambios desde despacho; puede ser necesaria una enmienda del plan y reevaluación de capacidades. No basta el dato «el avión es ETOPS 180». El EEP es una frontera de planificación, no una excusa para posponer la decisión hasta el último segundo.'},
        {title:'Cómo explicar la decisión',text:'Usa una estructura simple: qué cambió, qué requisito afecta, qué evidencia falta y qué opción conserva una salida segura. El objetivo del ejercicio es formular ese razonamiento con precisión. Las instrucciones reales de vuelo se obtienen del procedimiento aprobado y se coordinan con los responsables operacionales.'}
      ],takeaway:'Una decisión cambia cuando cambia la evidencia que la sostenía.',
      check:{q:'Un NOTAM elimina un alterno necesario para conservar la cobertura. ¿Qué demuestra preparación?',options:['Entrar porque la meteorología es buena.','Ignorarlo porque el despacho ya fue emitido.','Reevaluar y coordinar una alternativa o ruta válida antes de comprometer el segmento.'],correct:2,feedback:'Una autorización de diseño no devuelve disponibilidad a una pista cerrada.'}},
    {id:8,kicker:'DECIDIR',title:'Más cercano no siempre significa más útil',subtitle:'Tiempo, aptitud y condición de la aeronave deben leerse juntos.',time:'10–14 min',base:'PDF §0.14 · diapositiva 17 · quiz 19',refs:['BASE','DIV','FUEL','TLS'],lab:'diversion',
      goal:'Comparar alternativas sin reducir la decisión a NM ni a una cifra aislada de minutos.',
      blocks:[
        {title:'Motor inoperativo',text:'Para el bimotor del ejemplo FAA, 121.565 exige el aeropuerto adecuado más cercano en tiempo donde pueda hacerse un aterrizaje seguro. La frase tiene dos partes: tiempo y posibilidad de aterrizar con seguridad. La lista original de alternos no convierte un aeródromo inutilizable en apto ni excluye automáticamente otra opción evaluada como adecuada.'},
        {title:'Distancia dividida por GS no es todo el tiempo de llegada',text:'El laboratorio calcula un tiempo simplificado de crucero para mostrar el efecto del viento. Un vuelo real añade descenso, aproximación, restricciones, performance y condiciones. No debe utilizarse esa cuenta para emitir una recomendación de desvío en servicio. Aquí todos los datos son ficticios y la decisión se limita a los supuestos visibles.'},
        {title:'Primero la condición de la aeronave',text:'Control de vuelo, procedimientos de la falla, valoración de capacidades y coordinación con ATC y operaciones forman parte de la respuesta. Una despresurización exige considerar oxígeno y altitud segura; una falla de un sistema puede modificar la aptitud de un alterno o la desviación. El cronómetro ETOPS no sustituye el procedimiento de emergencia ni la autoridad del comandante.'},
        {title:'El desvío no termina al tocar pista',text:'El material incluye recuperación de pasajeros, comunicaciones y alternos remotos. Son parte del apoyo operacional y no una razón para descartar un aterrizaje necesario. El briefing debe distribuir tareas y comunicar intención, capacidades y necesidades. Para un evento real se aplican los requisitos del Estado y del operador, no el resultado de esta práctica.'}
      ],takeaway:'Busca el menor tiempo entre opciones realmente utilizables para la condición actual.',
      check:{q:'A: 500 NM / 300 kt, pista cerrada. B: 600 NM / 400 kt, utilizable. Con esos únicos supuestos, ¿qué comparación tiene sentido?',options:['A porque tiene menos millas.','B: 90 min de crucero, mientras A no es una opción de aterrizaje válida.','A: el cierre no importa después de una falla.'],correct:1,feedback:'Tiempo simplificado de B: 600/400×60=90 min. En la realidad hay que confirmar todas las condiciones y el tiempo total.'}},
    {id:9,kicker:'APLICAR',title:'Una misión. Tres cambios.',subtitle:'Integra autorización, campo, combustible y criterio sin memorizar una secuencia.',time:'12–18 min',base:'Síntesis de PDF §§0.9–0.15 · diapositivas 11–19',refs:['BASE','APP','ALT','EEP','FUEL','DIV'],lab:'mission',
      goal:'Justificar decisiones ante cambios del escenario y transferir el concepto a una configuración específica.',
      blocks:[
        {title:'Brief de la misión ficticia',text:'Operación de entrenamiento con un bimotor genérico. Autorización operacional: 120 minutos. Aeródromos Alfa, Bravo y Charlie: ficticios. No se usa matrícula, MEL, meteorología ni performance real. Cada tarjeta de novedad proporciona todos los supuestos necesarios para la pregunta; no intentes completar los vacíos con características de un A320.'},
        {title:'La secuencia de pensamiento',text:'Observa el cambio, identifica el requisito, comprueba la información disponible y elige una acción que puedas justificar. La retroalimentación explica por qué una opción es más sólida que las otras. Puedes repetir el caso; el propósito es aprender, no etiquetar la competencia operacional de una persona desde tres clics.'},
        {title:'Caso de aplicación A320: no una dependencia del curso',text:'Tus documentos cierran con la familia A320 y el valor de 180 minutos. Conservamos esa referencia como ejemplo de estudio, pero no afirmamos que cada variante, motor, matrícula y operador disponga hoy de idéntica capacidad. Para aplicarla, identifica AFM/configuración aprobada, documento CMP cuando corresponda, MEL y autorización operacional. Una tarjeta «A320» no prueba por sí sola el alcance ETOPS de un vuelo.'},
        {title:'Lo que se retiró como regla general',text:'No se publican como hechos universales las fechas de aprobación de toda la familia, «el operador nunca supera el diseño» sin considerar disposiciones específicas, ni «con un motor se pierde exactamente la mitad de los sistemas». Estas correcciones están trazadas en Fuentes y revisión. La clase sigue siendo introductoria y necesita adaptación autorizada antes de utilizarse como programa de un operador.'}
      ],takeaway:'La mejor respuesta une el cambio con el requisito; no repite una cifra fuera de contexto.',
      check:{q:'¿Qué evidencia necesitas antes de usar «180 min» en un avión concreto?',options:['Solo el nombre de la familia.','Configuración/documentos aplicables, aprobación del operador y condiciones del vuelo.','Una captura comercial del fabricante.'],correct:1,feedback:'Capacidad de diseño, autorización operacional y estado del vuelo son demostraciones diferentes.'}},
    {id:10,kicker:'CONSOLIDAR',title:'Comprueba tu criterio',subtitle:'20 preguntas revisadas. Después del resultado, vuelve a lo que necesitas.',time:'15–25 min',base:'etops-quiz.pdf · 20 preguntas, mapa de cobertura y criterio sugerido 80 %',refs:['BASE','FUEL','EEP','APP','DIV'],lab:'assessment',
      goal:'Reconocer qué conceptos dominas y qué módulos debes volver a trabajar.',
      blocks:[
        {title:'Dos maneras de practicar',text:'Modo Aprender: una pregunta por vez con retroalimentación inmediata, tal como propone el banco recibido. Modo Comprobar: responde las 20 y consulta la explicación al terminar. En ambos casos las opciones se barajan al iniciar un intento y la respuesta queda vinculada a su identificador, no a una letra fija.'},
        {title:'Qué significa 80 % aquí',text:'Se conserva el criterio formativo sugerido de 16/20. No es un umbral regulatorio ni una certificación ETOPS. El resultado pertenece a este banco de práctica, no mide por sí solo desempeño en vuelo. Cada respuesta errada lleva a un módulo concreto para repasar; el error no bloquea el aprendizaje.'},
        {title:'Trazabilidad de las preguntas',text:'Las 20 preguntas están adaptadas del banco original. Se corrigieron formulaciones que convertían supuestos en reglas: FAA/EDTO, punto crítico, escenario combinado, ventana de mínimos, sistemas limitados por tiempo y caso A320. La pregunta histórica se sustituyó por aplicación del concepto para priorizar comprensión; cada ítem conserva la referencia al número original.'}
      ],takeaway:'Un buen resultado sirve para orientar el repaso; no sustituye entrenamiento ni aprobación operacional.'}
  ],
  glossary:[
    ['ETOPS','Extended Operations (FAA); en el marco EASA, operaciones extendidas con aviones de dos motores. Lee la definición y aplicabilidad del marco concreto.'],
    ['EDTO','Extended Diversion Time Operations. Terminología OACI presentada en el material base; umbral fijado por el Estado del operador.'],
    ['OEI','One Engine Inoperative: un motor inoperativo. La velocidad aprobada de referencia no es automáticamente el groundspeed del día.'],
    ['TAS / GS','True Airspeed / Groundspeed: velocidad respecto al aire / respecto al suelo. El viento diferencia ambas.'],
    ['Threshold time','Tiempo umbral: determina cuándo entra en juego el marco aplicable. No es el máximo autorizado.'],
    ['Maximum diversion time','Tiempo máximo de desviación autorizado para la operación, sujeto a condiciones y limitaciones.'],
    ['EEP / EXP','ETOPS Entry Point / Exit Point: entrada/salida de un segmento más allá del umbral aplicable.'],
    ['ETP','Equal Time Point: igual tiempo hacia dos opciones bajo un escenario definido. No es automáticamente el punto crítico de combustible.'],
    ['Critical point','Punto más exigente para el cálculo de combustible del escenario. Se determina por análisis, no por el nombre de un punto.'],
    ['Adequate / suitable','Adecuación y aptitud requieren evaluar disponibilidad, instalaciones, servicios, condiciones de campo y criterios meteorológicos aplicables.'],
    ['MEL','Minimum Equipment List del operador. Sus condiciones pueden impedir ETOPS o limitar la operación.'],
    ['CMP','Configuration, Maintenance and Procedures: requisitos aplicables a la combinación avión–motor, cuando existe documento CMP.'],
    ['IFSD','In-Flight Shutdown. Cita siempre el denominador y el contexto de la tasa: diseño/flota mundial o seguimiento del operador.'],
    ['PDSC','Pre-departure Service Check ETOPS: comprobación específica previa y certificación según el programa autorizado.'],
    ['TLS','Time-Limited System: sistema cuya duración/capacidad temporal condiciona la planificación.'],
    ['OpSpecs','Operations Specifications: especificaciones operacionales autorizadas del operador.']
  ],
  revisions:[
    ['Aplicabilidad FAA','PDF p.2; PPT d.3; quiz 4','Se reemplaza «todos los modelos» por una definición con la exclusión de carga pura con más de dos motores y umbrales de Parte 121.','DEF'],
    ['EDTO y ETOPS','PDF p.3; quiz 3','Se conserva la afinidad conceptual, pero se evita afirmar equivalencia normativa exacta. No se verificó texto íntegro vigente del Anexo 6.','ICAO'],
    ['Historia y cifras de fiabilidad','PDF pp.4–5; PPT d.6–7; quiz 5','Hitos conservados como contexto del material base. Se retiran del examen las cifras 100×/60× y las fechas de certificación no corroboradas.','BASE'],
    ['ETP ≠ punto crítico universal','PDF pp.8,10; quiz 10','Se diferencian igualdad de tiempo y punto más exigente de combustible.','FUEL'],
    ['Escenario de combustible','PDF pp.10–11; PPT d.13; quiz 11','Se elimina la selección automática del caso combinado; se compara el mayor de los tres escenarios.','FUEL'],
    ['Altitud tras despresurización','PDF pp.10,14; PPT d.13,17','FL100 queda como ejemplo, no mandato general. Importan altitud segura, terreno, oxígeno y procedimiento.','FUEL'],
    ['Viento, hielo, deterioro y APU','PDF p.11; quiz 12','Se explican condiciones; «viento +5 %» no es aumentar favorablemente un viento de cola ni sumar siempre 5 % al combustible total.','FUEL'],
    ['Despacho vs EEP','PDF p.10; PPT d.12; quiz 14','FAA 121.631 distingue mínimos operacionales antes del EEP de mínimos ETOPS de despacho. No se autoriza continuar automáticamente por una sola cifra.','EEP'],
    ['Mínimos y ventanas','PDF pp.9–10; PPT d.12; quiz 13','Los incrementos se usan solo como supuestos didácticos. Se retiran la tabla CAT II/III y la ventana EASA ±1 h como reglas universales no verificadas.','ALT'],
    ['Capacidad menos 15 minutos','PDF p.11; quiz 15','El ejemplo 195−15 se circunscribe a FAA 121.633(a); más allá de 180 se distinguen criterios de incendio y otros sistemas.','TLS'],
    ['Mantenimiento dual','PDF p.12; quiz 16','No depende únicamente de que trabaje la misma persona: se incluyen limitación, supervisión y verificaciones cuando no puede evitarse.','MAINT'],
    ['Aprobación de diseño y operacional','PDF p.13; quiz 17','Se evita el «nunca» general: el Apéndice P tiene disposiciones específicas para 75/138/207 min, entre otras.','APP'],
    ['Tasas IFSD','PDF p.13; quiz 18','Se distinguen niveles de flota mundial de 21.4 y umbrales de revisión operacional de 121.374.','REL'],
    ['Selección de desvío','PDF p.14; quiz 19','Se conserva «más cercano en tiempo» y se añade aptitud para un aterrizaje seguro y alcance bimotor del ejemplo.','DIV'],
    ['A320','PDF p.15; PPT d.18; quiz 20','Solo caso de aplicación. No se certifican variantes ni se mezcla con A320 Foundations; se exigen documentos de configuración y autorización.','APP']
  ]
};
