/* Veyra ETOPS 2.0 — visual first. Source detail stays available on request. */
(() => {
'use strict';
const C=window.ETOPS_CONTENT,Q=window.ETOPS_QUIZ,$=id=>document.getElementById(id),main=$('main');
if(!C||!Q||!main){if(main)main.textContent='La clase no pudo cargar. Actualiza para volver a intentarlo.';return;}
const E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const N=(x,min,max,f)=>Number.isFinite(Number(x))?Math.max(min,Math.min(max,Number(x))):f;
const F=x=>Number(x).toLocaleString('es-CO',{maximumFractionDigits:1});
const KEY='veyra.classes.etops.v1';let storage=true,S={v:1,done:[],checks:{},notes:{},history:[],quiz:null,visualView:'inicio'};
try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(p&&p.v===1){S.done=Array.isArray(p.done)?[...new Set(p.done.filter(i=>Number.isInteger(i)&&i>0&&i<=10))]:[];for(const k of ['checks','notes'])if(p[k]&&typeof p[k]==='object'&&!Array.isArray(p[k]))S[k]=p[k];S.history=Array.isArray(p.history)?p.history.filter(h=>h&&Number.isInteger(h.score)&&h.score>=0&&h.score<=20&&typeof h.at==='string').slice(0,10):[];if(validQuiz(p.quiz))S.quiz=p.quiz;if(/^m([1-9]|10)$/.test(p.visualView))S.visualView=p.visualView;}}catch{storage=false;}
function validQuiz(q){return q&&['learn','test'].includes(q.mode)&&Array.isArray(q.order)&&q.order.length===20&&new Set(q.order).size===20&&q.order.every(i=>Q.some(x=>x.id===i))&&q.options&&q.order.every(i=>Array.isArray(q.options[i])&&q.options[i].length===4&&new Set(q.options[i]).size===4&&q.options[i].every(a=>Number.isInteger(a)&&a>=0&&a<4))&&Number.isInteger(q.index)&&q.index>=0&&q.index<20&&q.answers&&typeof q.answers==='object'&&Object.entries(q.answers).every(([i,a])=>Q.some(x=>x.id===Number(i))&&Number.isInteger(a)&&a>=0&&a<4)&&(!q.complete||Object.keys(q.answers).length===20);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(S));}catch{storage=false;}$('storage').textContent=storage?'Progreso local · solo este navegador':'Guardado no disponible · puedes seguir estudiando';}
const icons={plane:'M12 2v18m0-13L3 13v2l9-3 9 3v-2L12 7m0 10l-4 4m4-4l4 4',clock:'M12 7v5l4 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',map:'M2 6l6-3 8 3 6-3v16l-6 3-8-3-6 3V6m6-3v16m8-13v16',cloud:'M5 18h14a4 4 0 0 0 0-8 7 7 0 0 0-13-2 5 5 0 0 0-1 10',fuel:'M12 2C9 7 5 10 5 15a7 7 0 0 0 14 0c0-5-4-8-7-13m-3 13a3 3 0 0 0 3 3',shield:'M12 2L3 6v6c0 5 9 10 9 10s9-5 9-10V6L12 2m-5 10l3 3 7-7',check:'M4 4h16v18H4V4m4-2h8v4H8V2m-1 11l3 3 7-7',fork:'M12 22V12M12 12L4 4m8 8l8-8M4 4v6m0-6h6m10 0v6m0-6h-6',bolt:'M14 2L4 14h7l-1 8 10-13h-7l1-7',book:'M12 5C7 2 2 3 2 3v17s5-1 10 2c5-3 10-2 10-2V3s-5-1-10 2v17',tool:'M14 3a6 6 0 0 0-7 7L2 18a3 3 0 0 0 4 4l8-8a6 6 0 0 0 7-7l-5 4-3-3 4-5z',fire:'M13 2c2 7 8 8 7 14a8 8 0 0 1-16 0c0-3 2-5 3-7l2 4c3-4 4-7 4-11'};
function icon(k){return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[k]||icons.plane}"/></svg>`;}
const V=[
 ['Qué es ETOPS','Un vuelo normal. Una salida que debes conservar.','plane','ETOPS permite superar el umbral con aprobación. No limita la duración total del vuelo.','PPT 3–5 · PDF 0.1–0.4'],
 ['Dos tiempos. Dos funciones.','Umbral y máximo autorizado no son lo mismo.','clock','Umbral: cuándo empieza el marco. Máximo: hasta dónde permite llegar la autorización.','PPT 9 y 16 · PDF 0.7 y 0.13'],
 ['Minutos que se vuelven millas','Toca 60, 120 o 180 y observa el círculo.','map','Distancia = TAS OEI × minutos / 60. Referencia ISA, sin viento.','PPT 8 · PDF 0.6'],
 ['¿Sigue siendo un alterno?','Una pista no basta: también importan el tiempo y su disponibilidad.','cloud','Despacho y revisión antes del EEP tienen criterios distintos.','PPT 10–12 · PDF 0.8–0.9'],
 ['Tres escenarios. Un mayor requisito.','No adivines qué falla consume más. Compáralas.','fuel','El combustible crítico es el mayor resultado de los escenarios evaluados.','PPT 13 · PDF 0.10'],
 ['La seguridad tiene respaldo','Toca un sistema para ver qué aporta al desvío.','shield','Capacidad de sistemas, configuración y mantenimiento deben sostener la desviación.','PPT 14–15 · PDF 0.11–0.12'],
 ['Antes del EEP: vuelve a mirar','Recorre las cuatro comprobaciones del caso.','check','Una novedad puede cambiar la decisión antes de entrar al segmento.','PPT 11 y 17 · PDF 0.9 y 0.14'],
 ['Tiempo, no solo distancia','Dos opciones: ¿cuál te permite llegar antes?','fork','Compara tiempo entre aeródromos donde sea posible aterrizar con seguridad.','PPT 17 · PDF 0.14'],
 ['Tu turno: decide','Tres novedades. Una pregunta cada vez.','bolt','Relaciona lo que cambió con el requisito que afecta.','Síntesis PPT 11–18 · casos ficticios'],
 ['Comprueba lo aprendido','Una pregunta por pantalla. Aprende también del error.','book','20 preguntas · referencia formativa 16/20 · sin certificación operacional.','Banco recibido · 20 preguntas']
];
let view='inicio',m=1,mode='scene',vars={},asked=false,missionStep=0,missionAnswers=[],lastFocus=null;
const chapters=()=>V.map((v,i)=>`<button class="chapter" data-go="m${i+1}" type="button"><span>${icon(v[2])}</span><div><small>${String(i+1).padStart(2,'0')}</small><b>${E(v[0])}</b></div><em>${S.done.includes(i+1)?'✓':'→'}</em></button>`).join('');
function go(v){if(location.hash.slice(1)===v)route();else location.hash=v;}
function btn(t,a,c=''){return `<button class="btn ${c}" type="button" ${a}>${t}</button>`;}
function svg(body,label){return `<svg class="diagram" viewBox="0 0 700 420" role="img" aria-label="${E(label)}"><defs><pattern id="grid" width="35" height="35" patternUnits="userSpaceOnUse"><path d="M35 0H0V35" fill="none" stroke="#ffffff" stroke-opacity=".055"/></pattern></defs><rect width="700" height="420" fill="url(#grid)"/>${body}</svg>`;}
function text(x,y,t,cls=''){return `<text x="${x}" y="${y}" class="${cls}">${E(t)}</text>`;}
function plane(x,y,r=90,s=1){return `<g transform="translate(${x} ${y}) rotate(${r}) scale(${s})" class="aircraft"><path d="M0-32C4-30 4-24 4-15L33 7v7L4 5v16l9 8v5L0 29l-13 5v-5l9-8V5l-29 9V7L-4-15v-10Q-3-32 0-32Z" fill="currentColor"/></g>`;}
function airport(x,y,label){return `<g transform="translate(${x} ${y})"><rect x="-8" y="-22" width="16" height="44" rx="2" class="runway"/><path d="M0-18v6m0 5v6m0 5v6" stroke="#f8f3e6" stroke-width="2"/>${text(0,48,label,'airport-label')}</g>`;}
function line(x1,y1,x2,y2,cls='route'){return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" class="${cls}"/>`;}
function label(iconName,title,value){return `<div class="metric">${icon(iconName)}<div><small>${title}</small><strong>${value}</strong></div></div>`;}
function choices(id,rows,val){return `<div class="switches" role="group" aria-label="${E(id)}">${rows.map(([v,t])=>btn(t,`data-var="${id}" data-value="${v}" aria-pressed="${String(v)===String(val)}"`)).join('')}</div>`;}
function range(id,label,v,min,max,step=1,unit=''){return `<label class="slider">${label}<output id="out-${id}">${F(v)} ${unit}</output><input data-range="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${v}" aria-label="${E(label)}"></label>`;}
function stage(body,caption){return `<div class="exhibit"><div id="art">${body}</div><div class="exhibit-caption"><span class="pulse"></span>${caption}</div></div>`;}
function route(){view=location.hash.slice(1)||'inicio';if(!/^(inicio|m(?:[1-9]|10)|quiz)$/.test(view))view='inicio';if(/^m\d+$/.test(view)){m=Number(view.slice(1));S.visualView=view;vars={};asked=false;missionStep=0;missionAnswers=[];lesson();}else if(view==='quiz')quiz();else home();save();$('progress').textContent=S.done.length+'/10 revisados';$('track').style.width=S.done.length*10+'%';main.focus({preventScroll:true});window.scrollTo(0,0);}
function home(){const resume=S.visualView||'m1';main.innerHTML=`<section class="hero"><div class="hero-copy"><div class="eyebrow">OPERACIONES DE RANGO EXTENDIDO</div><h1>ETOPS</h1><h2>Si algo cambia,<br>¿cuál es tu salida?</h2><p>Una idea. Un gráfico. Tu decisión.<br>Mueve el alcance, compara y decide.</p>${btn(S.done.length?'Continuar recorrido →':'Comenzar →',`data-go="${S.done.length?resume:'m1'}"`,'gold')}<small>10 temas · práctica a tu ritmo</small></div>${stage(svg(`<path d="M0 300Q130 160 190 20l100-20-5 190-90 160L0 390Z" class="land"/><path d="M700 15L600 0 535 180 585 320 700 390Z" class="land"/><circle cx="175" cy="215" r="145" class="coverage"/><circle cx="545" cy="215" r="145" class="coverage"/><path d="M100 260Q350 65 615 250" class="route"/>${airport(175,215,'ALFA')}${airport(545,215,'BRAVO')}${plane(351,148,85,.9)}${text(350,62,'TIEMPO HASTA UNA OPCIÓN','center faint')}${text(350,354,'PLANIFICA · VERIFICA · DECIDE','center gold-text')}`,'Ruta conceptual, avión y dos aeródromos'),'Esquema conceptual · no es una carta de navegación')}</section><section class="home-ribbon"><span>${icon('map')}Mueve el alcance</span><span>${icon('fuel')}Compara combustible</span><span>${icon('fork')}Elige un desvío</span></section><div class="home-bottom"><p>Formación introductoria · una idea cada vez.<br><small>Explicaciones y precisiones disponibles cuando las necesites.</small></p>${btn('Ver recorrido',`data-dialog="map"`,'outline')}</div>`;}
function lesson(){const v=V[m-1];main.innerHTML=`<header class="lesson-heading"><div class="eyebrow">${String(m).padStart(2,'0')} / 10 · ${m===9?'DECIDE':'EXPLORA'}</div><h1>${v[0]}</h1><p>${v[1]}</p></header><section class="learning-stage" id="learningStage"><div id="visual"></div><aside class="interaction" id="interaction"></aside></section><div class="insight"><span>${icon('book')}</span><p>${v[3]}</p>${btn('Ver explicación',`data-dialog="detail"`,'link')}</div><footer class="lesson-nav">${btn('← Anterior',`data-go="${m===1?'inicio':'m'+(m-1)}"`,'outline')}<div class="dots" aria-label="Avance por módulos">${V.map((_,i)=>`<button type="button" data-go="m${i+1}" aria-label="Módulo ${i+1}" ${i===m-1?'aria-current="step"':''}>${S.done.includes(i+1)?'✓':i+1}</button>`).join('')}</div>${btn(m===10?'Ir a evaluación →':'Siguiente →',`data-next="${m}"`,'dark')}</footer>`;paint();}
function paint(silent=false){if(m===9){mission();return;}if(m===10){assessment();return;}const left=$('visual'),right=silent?document.createElement('aside'):$('interaction');
if(m===1){const p=N(vars.position??45,0,100,45),dist=400+p*8,t=Math.round(dist/400*60);left.innerHTML=stage(svg(`<circle cx="155" cy="215" r="140" class="coverage"/><circle cx="155" cy="215" r="140" class="threshold"/>${line(155,215,600,215)}${airport(155,215,'ALTERNO')}${plane(155+dist*.35,215,90,.7)}${text(350,65,'SI UN MOTOR QUEDA INOPERATIVO','center faint')}${text(465,315,t+' min','center number')}${text(465,346,'A LA OPCIÓN DEL EJEMPLO','center faint')}${text(157,123,'60 min','gold-text center')}`,'El avión se aleja del alterno y aumenta el tiempo de desvío'),'Bimotor del ejemplo FAA · OEI 400 kt · aire en calma');right.innerHTML=`<div class="eyebrow">MUEVE EL CONTROL</div><h2>¿Qué cambia al alejarte?</h2>${range('position','Posición en la ruta',p,0,100,5,'%')}${label('clock','Tiempo hasta el alterno',t+' min')}<p id="liveAnswer" class="answer" aria-live="polite">${t>60?'Más allá de 60 min: revisa la aprobación ETOPS aplicable.':'Hasta el umbral de 60 min de este ejemplo.'}</p>${btn('ETOPS / EDTO',`data-dialog="terms"`,'link')}${questionButton()}`;}
if(m===2){const auth=Number(vars.auth||120),mel=Number(vars.mel||180),limit=Math.min(180,auth,mel);left.innerHTML=stage(svg(`${text(350,46,'NO CONFUNDAS LA PUERTA CON EL TECHO','center faint')}<rect x="55" y="98" width="252" height="225" rx="14" class="frame"/><rect x="392" y="98" width="252" height="225" rx="14" class="frame"/>${text(180,139,'UMBRAL','center gold-text')}${text(180,224,'60','center huge')}${text(180,258,'MIN · SUPUESTO BIMOTOR','center faint')}${text(180,294,'Activa el marco','center')}${text(518,139,'MÁXIMO','center gold-text')}${text(518,224,limit,'center huge')}${text(518,258,'MIN · ESTE CASO','center faint')}${text(518,294,'Limita el alcance','center')}<path d="M329 211h43m-10-9l10 9-10 9" class="route"/>`,'Tiempo umbral de 60 minutos y máximo del caso'),'Diseño del caso: 180 min · autorización ordinaria');right.innerHTML=`<div class="eyebrow">COMPARA LOS LÍMITES</div><h2>El avión puede.<br>¿El vuelo también?</h2><label class="control-label">Autorización del operador</label>${choices('auth',[[120,'120 min'],[180,'180 min']],auth)}<label class="control-label">Condición MEL suministrada</label>${choices('mel',[[180,'Sin reducción'],[90,'Máximo 90']],mel)}<p class="answer" aria-live="polite">Este caso queda limitado a <strong>${limit} min</strong>.</p>${questionButton()}`;}
if(m===3){const time=Number(vars.time||120),w=N(vars.wind??0,-80,80,0),radius=400*time/60,x=1600*(400-w)/800;left.innerHTML=stage(svg(`<circle cx="120" cy="183" r="${radius*.23}" class="coverage"/><circle cx="580" cy="183" r="${radius*.23}" class="coverage"/>${line(120,183,580,183)}${airport(120,183,'ALFA')}${airport(580,183,'BRAVO')}${plane(350,183,90,.7)}${text(350,54,radius+' NM','center number')}${text(350,83,'RADIO A 400 KT OEI','center faint')}<path d="M80 321H620" class="threshold"/><circle cx="${80+x/1600*540}" cy="321" r="8" fill="#e6bc64"/>${text(80,350,'A')}${text(620,350,'B')}${text(350,391,'ETP: '+F(x)+' NM DESDE A','center gold-text')}`,'Círculos de alcance y posición del punto de tiempo igual'),'Arriba: alcance en aire en calma · abajo: ETP lineal A–B = 1.600 NM');right.innerHTML=`<div class="eyebrow">TOCA UN TIEMPO</div><h2>Más minutos.<br>Mayor radio.</h2>${choices('time',[[60,'60'],[120,'120'],[180,'180']],time)}<p class="formula">400 × ${time}/60 = <strong>${radius} NM</strong></p>${range('wind','Viento de cola hacia B',w,-80,80,10,'kt')}<p class="answer">El viento mueve el <strong>ETP</strong>, no la autorización.</p>${questionButton()}`;}
if(m===4){const phase=vars.phase||'dispatch',open=vars.open!=='no',ceil=N(vars.ceil??900,500,1200,900),required=phase==='dispatch'?1000:600,ok=open&&ceil>=required;left.innerHTML=stage(svg(`<path d="M0 260Q150 215 280 265T700 248V420H0Z" class="land"/><g transform="translate(245 50) scale(7)"><path d="${icons.cloud}" stroke="#9db1c0" stroke-width="1" fill="#263b4c"/></g><path d="M280 370l40-170h60l40 170" class="runway"/><path d="M350 348v-30m0-18v-24m0-18v-18" stroke="#edf0ee" stroke-width="4"/>${line(170,122,170,260,'threshold')}${text(85,196,ceil+' ft','gold-text')}${text(525,330,open?'ABIERTO':'CERRADO','center '+(open?'good-text':'warn-text'))}${text(350,395,'BRAVO · AERÓDROMO FICTICIO','center faint')}`,'Techo meteorológico sobre una pista y disponibilidad del alterno'),'Supuesto: base 600 ft / 1 SM · despacho +400 ft / +1 SM');right.innerHTML=`<div class="eyebrow">CAMBIA LA FASE</div><h2>Mismo aeropuerto.<br>Distinto filtro.</h2>${choices('phase',[['dispatch','Despacho'],['entry','Antes del EEP']],phase)}${range('ceil','Techo · ft sobre el campo',ceil,500,1200,100,'ft')}${choices('open',[['yes','Abierto'],['no','Cerrado']],open?'yes':'no')}<p class="answer ${ok?'positive':'caution'}" aria-live="polite"><strong>${ok?'Cumple':'No cumple'}</strong> estos filtros. Techo requerido: ${required} ft. Visibilidad del caso: 2 SM.</p>${questionButton()}`;}
if(m===5){const p=Number(vars.fuel||1),a=p===1?[5400,6600,6000]:[5200,6100,7500],mx=Math.max(...a),winner=a.indexOf(mx);left.innerHTML=stage(svg(`${text(350,45,'COMPARA DESDE EL MISMO PUNTO','center faint')}${['Motor inoperativo','Despresurización','Ambas'].map((n,i)=>`${text(40,95+i*103,n,'chart-label')}<rect x="40" y="${112+i*103}" width="${a[i]/8000*550}" height="30" rx="4" fill="${i===winner?'#e6bc64':'#446078'}"/>${text(610,135+i*103,F(a[i]),'chart-value')}`).join('')}${text(350,402,'KG · CANTIDADES COMPLETAS DEL EJERCICIO','center faint')}`,'Comparación gráfica de combustible de los tres escenarios'),'Datos ficticios para aprender · no performance de una aeronave');right.innerHTML=`<div class="eyebrow">¿CUÁL MANDA?</div><h2>El mayor cálculo.<br>No el nombre de la falla.</h2>${choices('fuel',[[1,'Caso A'],[2,'Caso B']],p)}${label('fuel','Requisito mayor',F(mx)+' kg')}<p class="answer" aria-live="polite">En este caso manda <strong>${['motor inoperativo','despresurización','el escenario combinado'][winner]}</strong>.</p>${btn('Qué incluye el cálculo',`data-dialog="fuel"`,'link')}${questionButton()}`;}
if(m===6){const sys=vars.system||'fire',a={bolt:['Energía','Fuentes independientes para sostener la desviación.'],cloud:['Presurización','Oxígeno y altitud segura según la situación.'],fire:['Incendio en bodega','La duración certificada condiciona la planificación.'],tool:['Mantenimiento','PDSC, aceite, APU y control del mantenimiento dual.']}[sys];left.innerHTML=stage(svg(`${text(350,45,'QUÉ RESPALDA LA DESVIACIÓN','center faint')}${plane(350,211,0,3)}<circle cx="350" cy="211" r="151" class="threshold"/>${[['bolt',140,134],['cloud',552,134],['fire',140,315],['tool',552,315]].map(([n,x,y])=>`<g transform="translate(${x-22} ${y-22})" class="svg-control" role="button" tabindex="0" data-svg-system="${n}" aria-label="${{bolt:'Eléctrico',cloud:'Presurización',fire:'Incendio',tool:'Mantenimiento'}[n]}"><circle cx="22" cy="22" r="44" fill="transparent"/><circle cx="22" cy="22" r="34" fill="${n===sys?'#c9a45d':'#203446'}"/><path d="${icons[n]}" transform="translate(2 2) scale(1.7)" fill="none" stroke="${n===sys?'#07111f':'#c5d2dc'}" stroke-width="1.3"/></g>`).join('')}${text(350,402,'AERONAVE GENÉRICA · NO DIAGRAMA DE SISTEMAS','center faint')}`,'Aeronave genérica y símbolos de los sistemas de respaldo'),'Ejemplo FAA hasta 180 min: 195 min de capacidad − 15 min = 180 min');right.innerHTML=`<div class="eyebrow">TOCA UN SÍMBOLO</div><h2>No es solo<br>el motor.</h2><div class="system-buttons">${[['bolt','Eléctrico'],['cloud','Presurización'],['fire','Incendio'],['tool','Mantenimiento']].map(([k,t])=>btn(icon(k)+t,`data-var="system" data-value="${k}" aria-pressed="${sys===k}"`)).join('')}</div><p class="answer" aria-live="polite"><strong>${a[0]}.</strong> ${a[1]}</p>${questionButton()}`;}
if(m===7){const step=N(vars.step??0,0,3,0),items=[['cloud','Alternos','Disponibilidad y meteorología actualizadas.'],['shield','Sistemas','Capacidades y diferidos que afectan ETOPS.'],['fuel','Combustible','Comparar lo disponible con lo requerido.'],['check','Coordinación','Revisar cambios con despacho y tripulación.']];left.innerHTML=stage(svg(`${line(65,205,635,205)}${plane(125+step*100,205,90,.6)}<path d="M510 87v254" class="threshold"/>${text(510,69,'EEP','center gold-text')}${text(590,361,'SEGMENTO','center faint')}${items.map(([k,t],i)=>`<g transform="translate(${70+i*120} 90)"><circle cx="40" cy="32" r="32" fill="${i===step?'#c9a45d':'#1d3548'}"/><path d="${icons[k]}" transform="translate(23 15) scale(1.4)" fill="none" stroke="${i===step?'#07111f':'#a6b9c8'}" stroke-width="1.5"/></g>${text(110+i*120,285,String(i+1).padStart(2,'0'),'center gold-text')}`).join('')}${text(300,350,'VERIFICAR ANTES DE ENTRAR','center faint')}`,'Cuatro comprobaciones antes de la línea EEP'),'Una comprobación del ejemplo, no una lista operacional de chequeo');right.innerHTML=`<div class="eyebrow">ETOPS CHECK</div><h2>Antes de la línea.</h2>${choices('step',items.map((x,i)=>[i,String(i+1).padStart(2,'0')]),step)}${label(items[step][0],items[step][1],String(step+1)+' / 4')}<p class="answer" aria-live="polite">${items[step][2]}</p>${questionButton()}`;}
if(m===8){const open=vars.bravo!=='no',best=open?'BRAVO':'CHARLIE',time=open?90:105;left.innerHTML=stage(svg(`${plane(120,210,90,.8)}${line(164,204,548,121,open?'route':'unavailable')}${line(164,222,548,317,open?'threshold':'route')}${airport(570,121,'BRAVO')}${airport(570,317,'CHARLIE')}${text(350,132,'600 NM / 400 kt','center')}${text(350,161,'90 min','center number small-number')}${text(350,282,'420 NM / 240 kt','center')}${text(350,315,'105 min','center number small-number')}${text(350,51,'MENOS MILLAS ≠ MENOS MINUTOS','center gold-text')}`,'Dos rutas de desvío comparando tiempo, distancia y disponibilidad'),'Tiempo de crucero simplificado · no incluye descenso ni aproximación');right.innerHTML=`<div class="eyebrow">COMPARA OPCIONES</div><h2>¿Y si Bravo cierra?</h2>${choices('bravo',[['yes','Bravo abierto'],['no','Bravo cerrado']],open?'yes':'no')}${label('clock','Menor tiempo utilizable',time+' min')}<p class="answer" aria-live="polite"><strong>${best}</strong> es la opción del ejercicio. No basta elegir menos NM.</p>${questionButton()}`;}
if(silent){for(const selector of ['.answer','.metric','.formula']){const old=$('interaction').querySelector(selector),fresh=right.querySelector(selector);if(old&&fresh){old.innerHTML=fresh.innerHTML;old.className=fresh.className;}}}
}
function questionButton(){return btn('Comprueba tu idea →','data-check-open','dark check-trigger');}
function showCheck(){const ch=C.modules[m-1].check;if(!ch)return;asked=true;const right=$('interaction');right.innerHTML=`<div class="eyebrow">TU DECISIÓN</div><h2 class="question-title">${E(ch.q)}</h2><div class="answers">${ch.options.map((x,i)=>btn(`<span>${String.fromCharCode(65+i)}</span>${E(x)}`,`data-check="${i}"`,'option')).join('')}</div><div id="feedback" role="status"></div>${btn('← Volver al gráfico','data-return-scene','link')}`;}
const cases=[['Bravo cerrará antes de tu llegada.','Sin Bravo, una parte de la ruta queda fuera de los 120 min autorizados.','¿Qué haces antes del EEP?',['Entrar: el diseño es ETOPS 180.','Reevaluar y coordinar otra opción o ruta válida.','Entrar: el pronóstico sigue siendo bueno.'],1,'Cambió la disponibilidad. Hay que recuperar una opción válida, no cambiar la autorización en el papel.'],['El consumo no sigue tu intuición.','OEI: 5.400 kg · Despresurización: 6.600 kg · Ambas: 6.000 kg. Disponible: 6.200 kg.','¿Qué muestra el cálculo?',['Faltan 400 kg frente al caso limitante.','Sobran 200 kg: siempre manda el combinado.','Con autorización 180, está cubierto.'],0,'6.600 − 6.200 = 400 kg. Se compara el mayor requisito desde el mismo punto.'],['El más cercano tiene más minutos.','Bravo: 90 min, utilizable. Charlie: 105 min, utilizable y más cercano en NM.','En este supuesto bimotor, ¿qué opción eliges?',['Charlie: menos millas.','El destino programado.','Bravo: menor tiempo y utilizable.'],2,'Tiempo y posibilidad de aterrizar con seguridad van juntos.']];
function mission(){if(missionStep>=3){const score=missionAnswers.filter((x,i)=>x===cases[i][4]).length;$('visual').innerHTML=stage(svg(`<circle cx="350" cy="198" r="123" class="coverage"/>${text(350,218,score+'/3','center huge')}${text(350,58,'MISIÓN COMPLETADA','center gold-text')}${text(350,375,'EL OBJETIVO ES EXPLICAR LA DECISIÓN','center faint')}`,'Resultado de las tres decisiones'),'Práctica formativa con datos ficticios');$('interaction').innerHTML=`<div class="eyebrow">CIERRE</div><h2>¿Qué cambió<br>en cada caso?</h2><p>Alterno. Combustible. Tiempo.<br>La decisión depende de la evidencia.</p>${btn('Repetir misión','data-mission-restart','outline')}${btn('Evaluación →','data-go="m10"','dark')}`;return;}const c=cases[missionStep];$('visual').innerHTML=stage(svg(`${line(110,240,590,240)}${airport(110,240,'ALFA')}${airport(590,240,'BRAVO')}${plane(300+missionStep*50,240,90,.9)}${text(350,59,'NOVEDAD '+(missionStep+1)+' / 3','center gold-text')}<circle cx="590" cy="240" r="95" class="threshold"/>${text(350,139,['ALTERNO','COMBUSTIBLE','TIEMPO'][missionStep],'center number small-number')}${text(350,360,'OBSERVA → RELACIONA → DECIDE','center faint')}`,'Ruta ficticia y novedad del escenario'),'Autorización del caso: 120 min · sin aeronave específica');$('interaction').innerHTML=`<div class="eyebrow">NOVEDAD ${missionStep+1} / 3</div><h2>${c[0]}</h2><p>${c[1]}</p><strong class="mission-question">${c[2]}</strong><div class="answers">${c[3].map((t,i)=>btn(t,`data-mission="${i}"`,'option')).join('')}</div><div id="feedback" role="status"></div>`;}
function assessment(){$('visual').innerHTML=stage(svg(`<g fill="none" stroke="#c9a45d" stroke-width="2"><rect x="205" y="65" width="290" height="290" rx="12"/><path d="M235 130l12 12 25-30m20 13h165M235 204l12 12 25-30m20 13h165M235 278l12 12 25-30m20 13h165"/></g>${text(350,395,'UNA PREGUNTA CADA VEZ','center faint')}`,'Ficha de evaluación con preguntas individuales'),'Banco recibido: 20 preguntas adaptadas · 80 % solo formativo');$('interaction').innerHTML=`<div class="eyebrow">20 PREGUNTAS</div><h2>Entiende tu resultado.</h2><p>Recibe una explicación y vuelve al concepto que necesitas repasar.</p>${btn(S.quiz&&!S.quiz.complete?'Retomar intento →':'Comenzar →','data-go="quiz"','dark')}<small>Sin tiempo límite.<br>No es una certificación ETOPS.</small>`;}
function shuffle(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
function quiz(){const qz=S.quiz;if(!qz){main.innerHTML=`<header class="lesson-heading"><div class="eyebrow">EVALUACIÓN FORMATIVA</div><h1>Una pregunta. Una decisión.</h1><p>20 preguntas del banco recibido, con las precisiones de la revisión técnica.</p></header><div class="quiz-modes"><article>${icon('book')}<h2>Aprender</h2><p>Explicación después de cada respuesta.</p>${btn('Iniciar práctica','data-start="learn"','gold')}</article><article>${icon('check')}<h2>Comprobar</h2><p>Responde todo y revisa al terminar.</p>${btn('Iniciar evaluación','data-start="test"','dark')}</article></div><p class="quiet">16/20 es la referencia formativa sugerida. No acredita una aprobación operacional.</p>${btn('← Clase','data-go="m10"','outline')}`;return;}if(qz.complete){result();return;}const q=Q.find(x=>x.id===qz.order[qz.index]),a=qz.answers[q.id],reveal=qz.mode==='learn'&&a!==undefined;main.innerHTML=`<header class="lesson-heading"><div class="eyebrow">${qz.mode==='learn'?'APRENDER':'COMPROBAR'} · ${qz.index+1} / 20</div><h1 class="quiz-title">${E(q.q)}</h1></header><section class="quiz-work"><div class="quiz-symbol">${icon(V[q.m-1][2])}<strong>${String(qz.index+1).padStart(2,'0')}</strong><span>${E(V[q.m-1][0])}</span></div><div><div class="answers">${qz.options[q.id].map((j,i)=>btn(`<span>${String.fromCharCode(65+i)}</span>${E(q.o[j])}`,`data-answer="${j}" ${a!==undefined?'disabled':''}`,'option '+(a===j?'chosen ':'')+(reveal&&j===q.a?'correct':'') )).join('')}</div>${a!==undefined?`<div class="feedback ${reveal&&a===q.a?'correct':''}" role="status">${reveal?`<b>${a===q.a?'Correcto.':'Revisa esta idea.'}</b> ${E(q.f)}`:'Respuesta guardada. Revisarás la explicación al finalizar.'}</div>`:''}<div class="quiz-nav">${btn('← Anterior',`data-quiz-prev ${qz.index===0?'disabled':''}`,'outline')}${btn(qz.index===19?'Ver resultado':'Siguiente →',`data-quiz-next ${a===undefined?'disabled':''}`,'dark')}</div></div></section><div class="home-bottom">${btn('Volver a la clase','data-go="m10"','link')}${btn('Reiniciar intento','data-reset-quiz','link')}</div>`;}
function result(){const score=Q.filter(q=>S.quiz.answers[q.id]===q.a).length,weak=[...new Set(Q.filter(q=>S.quiz.answers[q.id]!==q.a).map(q=>q.m))];main.innerHTML=`<section class="result"><div class="score">${score}<small>/20</small></div><div><div class="eyebrow">${score*5} % · FORMACIÓN</div><h1>${score>=16?'Referencia alcanzada.':'Un repaso con dirección.'}</h1><p>El resultado orienta el repaso. No certifica una competencia operacional.</p></div></section><h2 class="section-title">${weak.length?'Vuelve a estos conceptos':'Sigue consolidando'}</h2><div class="review-chapters">${(weak.length?weak:[3,5,8]).map(i=>btn(icon(V[i-1][2])+V[i-1][0],`data-go="m${i}"`,'outline')).join('')}</div><details class="result-detail"><summary>Revisar las 20 respuestas</summary>${S.quiz.order.map(id=>{const q=Q.find(x=>x.id===id);return `<article><h3>${E(q.q)}</h3><p>Tu respuesta: ${E(q.o[S.quiz.answers[q.id]])}</p><p><strong>Referencia:</strong> ${E(q.o[q.a])}</p><p>${E(q.f)}</p></article>`;}).join('')}</details><div class="quiz-nav">${btn('Nuevo intento','data-reset-quiz','dark')}${btn('Volver a ETOPS','data-go="inicio"','outline')}</div>`;}
function dialog(kind){lastFocus=document.activeElement;const d=$('dialog');if(d.open)d.close();let h='';if(kind==='map'){h=`<h2>Tu recorrido</h2><p>Elige un concepto. No necesitas leerlo todo para empezar a practicar.</p><div class="chapter-grid">${chapters()}</div><div class="quiz-nav">${btn('Glosario','data-dialog="glossary"','outline')}${btn('Fuentes','data-dialog="sources"','outline')}</div>`;}
if(kind==='detail'){const o=C.modules[m-1];h=`<div class="eyebrow">CONSULTA OPCIONAL · ${V[m-1][4]}</div><h2>${E(V[m-1][0])}</h2>${o.blocks.map(b=>`<details><summary>${E(b.title)}</summary><p>${E(b.text)}</p></details>`).join('')}<label class="note">Mi idea para recordar<textarea id="note" maxlength="3000" placeholder="Escribe tu nota…"></textarea></label><p class="quiet" id="note-status">Solo en este navegador. No escribas datos de tripulaciones.</p>${btn('Fuentes y precisiones','data-dialog="sources"','outline')}`;}
if(kind==='sources'){h=`<div class="eyebrow">CONTENIDO Y PROCEDENCIA</div><h2>Fuentes y precisiones</h2><p>La ruta visual retoma el nivel introductorio del PDF y la presentación recibidos. Las notas de corrección de la primera edición se conservan, separadas de la lectura principal.</p><p>Los escenarios numéricos son ficticios. No se ha hecho una nueva revisión normativa en esta actualización visual.</p>${C.revisions.map(([t,p,c])=>`<details><summary>${E(t)}</summary><small>${E(p)}</small><p>${E(c)}</p></details>`).join('')}<h3>Referencias de la edición anterior</h3>${C.sources.map(s=>`<article class="source"><strong>${E(s.title)}</strong><p>${E(s.detail)}</p>${s.url?`<a href="${E(s.url)}" target="_blank" rel="noopener noreferrer">Abrir referencia ↗</a>`:''}</article>`).join('')}`;}
if(kind==='terms'||kind==='glossary'){h=`<h2>${kind==='terms'?'ETOPS / EDTO':'Glosario'}</h2><label class="note">Buscar<input id="glossary-search" type="search" placeholder="EEP, tiempo, combustible…"></label><div id="glossary-list">${glossaryHTML(kind==='terms'?'ET':'')}</div>`;}
if(kind==='fuel'){h=`<div class="eyebrow">DEL MATERIAL BASE · ADAPTACIÓN</div><h2>¿Qué hay dentro del cálculo?</h2><div class="fuel-components">${[['plane','Descenso y crucero','Hasta el alterno, a la altitud del escenario.'],['clock','Espera y aproximación','15 min a 1.500 ft, aproximación y aterrizaje.'],['cloud','Viento, hielo y deterioro','Ajustes según el método aplicable.'],['bolt','APU','Cuando se requiere como fuente.']].map(([i,t,d])=>`<article>${icon(i)}<h3>${t}</h3><p>${d}</p></article>`).join('')}</div><p>Se calcula el punto más crítico; un ETP no es automáticamente ese punto. No se presupone FL100 para todo caso: importa la altitud segura y el oxígeno.</p>${btn('Ver precisión técnica','data-dialog="sources"','outline')}`;}
$('dialogBody').innerHTML=h;d.showModal();if($('note'))$('note').value=typeof S.notes[m]==='string'?S.notes[m]:'';}
function glossaryHTML(term){return C.glossary.filter(x=>x.join(' ').toLowerCase().includes(term.toLowerCase())).map(([t,d])=>`<article class="source"><h3>${E(t)}</h3><p>${E(d)}</p></article>`).join('')||'<p>No hay coincidencias.</p>';}
document.addEventListener('click',e=>{if(!(e.target instanceof Element))return;const spot=e.target.closest('[data-svg-system]');if(spot){vars.system=spot.dataset.svgSystem;paint();return;}const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.go){if($('dialog').open)$('dialog').close();go(b.dataset.go);return;}if(b.dataset.dialog){dialog(b.dataset.dialog);return;}if(b.hasAttribute('data-close')){$('dialog').close();return;}if(b.hasAttribute('data-next')){if(!S.done.includes(m))S.done.push(m);save();go(m===10?'quiz':'m'+(m+1));return;}if(b.dataset.var){vars[b.dataset.var]=b.dataset.value;paint();return;}if(b.hasAttribute('data-check-open')){showCheck();return;}if(b.hasAttribute('data-return-scene')){asked=false;paint();return;}if(b.hasAttribute('data-check')){const i=Number(b.dataset.check),c=C.modules[m-1].check;S.checks[m]=i;save();$('feedback').innerHTML=`<div class="feedback ${i===c.correct?'correct':''}"><b>${i===c.correct?'Correcto.':'Prueba de nuevo.'}</b> ${E(c.feedback)}</div>`;return;}if(b.hasAttribute('data-mission')){const a=Number(b.dataset.mission),c=cases[missionStep];missionAnswers[missionStep]=a;document.querySelectorAll('[data-mission]').forEach(x=>x.disabled=true);$('feedback').innerHTML=`<div class="feedback ${a===c[4]?'correct':''}">${c[5]}</div>${btn(missionStep===2?'Ver cierre':'Siguiente novedad →','data-mission-next','dark')}`;return;}if(b.hasAttribute('data-mission-next')){missionStep++;mission();return;}if(b.hasAttribute('data-mission-restart')){missionStep=0;missionAnswers=[];mission();return;}if(b.dataset.start){S.quiz={mode:b.dataset.start,order:shuffle(Q.map(q=>q.id)),options:Object.fromEntries(Q.map(q=>[q.id,shuffle([0,1,2,3])])),index:0,answers:{},complete:false};save();quiz();return;}if(b.hasAttribute('data-answer')){const id=S.quiz.order[S.quiz.index];if(S.quiz.answers[id]===undefined)S.quiz.answers[id]=Number(b.dataset.answer);save();quiz();return;}if(b.hasAttribute('data-quiz-prev')){S.quiz.index--;save();quiz();return;}if(b.hasAttribute('data-quiz-next')){if(S.quiz.index===19){if(Object.keys(S.quiz.answers).length!==20)return;S.quiz.complete=true;S.history.unshift({score:Q.filter(q=>S.quiz.answers[q.id]===q.a).length,at:new Date().toISOString(),mode:S.quiz.mode});S.history=S.history.slice(0,10);if(!S.done.includes(10))S.done.push(10);}else S.quiz.index++;save();quiz();$('progress').textContent=S.done.length+'/10 revisados';return;}if(b.hasAttribute('data-reset-quiz')){if(S.quiz&&!S.quiz.complete&&!confirm('¿Reiniciar el intento actual?'))return;S.quiz=null;save();quiz();}});

document.addEventListener('input',e=>{const t=e.target;if(t.matches('[data-range]')){vars[t.dataset.range]=t.value;paint(true);$('out-'+t.dataset.range).textContent=F(Number(t.value))+' '+({position:'%',wind:'kt',ceil:'ft'}[t.dataset.range]||'');}else if(t.id==='note'){S.notes[m]=t.value.slice(0,3000);save();$('note-status').textContent=storage?'Nota guardada.':'No se pudo guardar en este navegador.';}else if(t.id==='glossary-search')$('glossary-list').innerHTML=glossaryHTML(t.value);});
document.addEventListener('keydown',e=>{if(e.target instanceof Element&&e.target.matches('[data-svg-system]')&&['Enter',' '].includes(e.key)){e.preventDefault();vars.system=e.target.dataset.svgSystem;paint();}});
$('dialog').addEventListener('close',()=>{if(lastFocus&&lastFocus.isConnected)lastFocus.focus();});
window.addEventListener('hashchange',route);route();
})();
